version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: /gunicorn.sh
    ports:
      - "8011:8011"

  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx
    depends_on:
      - django

    ports:
      - "80:80"